version: '3.8'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  database:
    container_name: database
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
   driver: local